/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'accounts': RouteRecordInfo<'accounts', '/accounts', Record<never, never>, Record<never, never>>,
    'accounts-id': RouteRecordInfo<'accounts-id', '/accounts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'all-shipment': RouteRecordInfo<'all-shipment', '/AllShipment', Record<never, never>, Record<never, never>>,
    'annex-forms': RouteRecordInfo<'annex-forms', '/AnnexForms', Record<never, never>, Record<never, never>>,
    'authorization': RouteRecordInfo<'authorization', '/Authorization', Record<never, never>, Record<never, never>>,
    'caption-generator': RouteRecordInfo<'caption-generator', '/caption-generator', Record<never, never>, Record<never, never>>,
    'checklist-management': RouteRecordInfo<'checklist-management', '/checklist-management', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'delivery-receipts': RouteRecordInfo<'delivery-receipts', '/DeliveryReceipts', Record<never, never>, Record<never, never>>,
    'installation': RouteRecordInfo<'installation', '/installation', Record<never, never>, Record<never, never>>,
    'installation-id': RouteRecordInfo<'installation-id', '/installation/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'installation-details': RouteRecordInfo<'installation-details', '/InstallationDetails', Record<never, never>, Record<never, never>>,
    'installation-list': RouteRecordInfo<'installation-list', '/InstallationList', Record<never, never>, Record<never, never>>,
    'installation-photos': RouteRecordInfo<'installation-photos', '/InstallationPhotos', Record<never, never>, Record<never, never>>,
    'interview-scheduler': RouteRecordInfo<'interview-scheduler', '/interview-scheduler', Record<never, never>, Record<never, never>>,
    'invoice-history': RouteRecordInfo<'invoice-history', '/invoice-history', Record<never, never>, Record<never, never>>,
    'invoices-history': RouteRecordInfo<'invoices-history', '/invoices-history', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'manage-accounts': RouteRecordInfo<'manage-accounts', '/manage-accounts', Record<never, never>, Record<never, never>>,
    'messages': RouteRecordInfo<'messages', '/messages', Record<never, never>, Record<never, never>>,
    'my-profile': RouteRecordInfo<'my-profile', '/my-profile', Record<never, never>, Record<never, never>>,
    'my-proposals': RouteRecordInfo<'my-proposals', '/my-proposals', Record<never, never>, Record<never, never>>,
    'my-templates': RouteRecordInfo<'my-templates', '/my-templates', Record<never, never>, Record<never, never>>,
    'notification-settings': RouteRecordInfo<'notification-settings', '/notification-settings', Record<never, never>, Record<never, never>>,
    'notifications': RouteRecordInfo<'notifications', '/notifications', Record<never, never>, Record<never, never>>,
    'oas-upload': RouteRecordInfo<'oas-upload', '/OasUpload', Record<never, never>, Record<never, never>>,
    'password-login-info': RouteRecordInfo<'password-login-info', '/password-login-info', Record<never, never>, Record<never, never>>,
    'performance-overview': RouteRecordInfo<'performance-overview', '/performance-overview', Record<never, never>, Record<never, never>>,
    'platform-reports': RouteRecordInfo<'platform-reports', '/platform-reports', Record<never, never>, Record<never, never>>,
    'portfolio': RouteRecordInfo<'portfolio', '/portfolio', Record<never, never>, Record<never, never>>,
    'precommissioning-report': RouteRecordInfo<'precommissioning-report', '/PrecommissioningReport', Record<never, never>, Record<never, never>>,
    'project-reports': RouteRecordInfo<'project-reports', '/project-reports', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'security-login': RouteRecordInfo<'security-login', '/security-login', Record<never, never>, Record<never, never>>,
    'technician-profile': RouteRecordInfo<'technician-profile', '/technician-profile', Record<never, never>, Record<never, never>>,
    'technician-dashboard': RouteRecordInfo<'technician-dashboard', '/TechnicianDashboard', Record<never, never>, Record<never, never>>,
    'technicians': RouteRecordInfo<'technicians', '/technicians', Record<never, never>, Record<never, never>>,
    'technicians-id': RouteRecordInfo<'technicians-id', '/technicians/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'tracking-map': RouteRecordInfo<'tracking-map', '/TrackingMap', Record<never, never>, Record<never, never>>,
    'upgrade-plan': RouteRecordInfo<'upgrade-plan', '/upgrade-plan', Record<never, never>, Record<never, never>>,
    'upload-database': RouteRecordInfo<'upload-database', '/UploadDatabase', Record<never, never>, Record<never, never>>,
    'vehicles-drivers': RouteRecordInfo<'vehicles-drivers', '/VehiclesDrivers', Record<never, never>, Record<never, never>>,
    'warehouses': RouteRecordInfo<'warehouses', '/Warehouses', Record<never, never>, Record<never, never>>,
  }
}
